TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += oercone.db
DATA += oercone.proto

#=======================================
include $(TOP)/configure/RULES
